name: Release

on: [pull_request, push]

jobs:
  windows:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: install
        run: sudo apt install mingw-w64

      - name: make x86-64
        run: cd src && make clean && make -j build COMP=mingw ARCH=x86-64 EXE=fairy-stockfish_x86-64.exe && strip fairy-stockfish_x86-64.exe

      - name: make x86-64-modern
        run: cd src && make clean && make -j build COMP=mingw ARCH=x86-64-modern EXE=fairy-stockfish_x86-64-modern.exe && strip fairy-stockfish_x86-64-modern.exe

      - name: make x86-64-bmi2
        run: cd src && make clean && make -j build COMP=mingw ARCH=x86-64-bmi2 EXE=fairy-stockfish_x86-64-bmi2.exe && strip fairy-stockfish_x86-64-bmi2.exe

      - name: make largeboards x86-64
        run: cd src && make clean && make -j build COMP=mingw ARCH=x86-64 EXE=fairy-stockfish-largeboards_x86-64.exe largeboards=yes && strip fairy-stockfish-largeboards_x86-64.exe

      - name: make largeboards x86-64-modern
        run: cd src && make clean && make -j build COMP=mingw ARCH=x86-64-modern EXE=fairy-stockfish-largeboards_x86-64-modern.exe largeboards=yes && strip fairy-stockfish-largeboards_x86-64-modern.exe

      - name: make largeboards x86-64-bmi2
        run: cd src && make clean && make -j build COMP=mingw ARCH=x86-64-bmi2 EXE=fairy-stockfish-largeboards_x86-64-bmi2.exe largeboards=yes && strip fairy-stockfish-largeboards_x86-64-bmi2.exe

      - uses: actions/upload-artifact@v2
        with:
          name: fairy-stockfish
          path: src/fairy-stockfish*.exe

  linux:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: make x86-64
        run: cd src && make clean && make -j build COMP=gcc ARCH=x86-64 EXE=fairy-stockfish_x86-64 && strip fairy-stockfish_x86-64

      - name: make x86-64-modern
        run: cd src && make clean && make -j build COMP=gcc ARCH=x86-64-modern EXE=fairy-stockfish_x86-64-modern && strip fairy-stockfish_x86-64-modern

      - name: make x86-64-bmi2
        run: cd src && make clean && make -j build COMP=gcc ARCH=x86-64-bmi2 EXE=fairy-stockfish_x86-64-bmi2 && strip fairy-stockfish_x86-64-bmi2

      - name: make largeboards x86-64
        run: cd src && make clean && make -j build COMP=gcc ARCH=x86-64 EXE=fairy-stockfish-largeboards_x86-64 largeboards=yes && strip fairy-stockfish-largeboards_x86-64

      - name: make largeboards x86-64-modern
        run: cd src && make clean && make -j build COMP=gcc ARCH=x86-64-modern EXE=fairy-stockfish-largeboards_x86-64-modern largeboards=yes && strip fairy-stockfish-largeboards_x86-64-modern

      - name: make largeboards x86-64-bmi2
        run: cd src && make clean && make -j build COMP=gcc ARCH=x86-64-bmi2 EXE=fairy-stockfish-largeboards_x86-64-bmi2 largeboards=yes && strip fairy-stockfish-largeboards_x86-64-bmi2

      - uses: actions/upload-artifact@v2
        with:
          name: fairy-stockfish
          path: src/fairy-stockfish*
